système temps réel - TP2: do_work
do_work()
void * do_work (long unsigned int duration)
Simulation of work on CPU during x ms.
Parameters
duration Task's duration
Returns
void*
Definition at line 15 of file 1-introduction.h.
{
    duration = duration * DO_WORK_TIME_1S_MS;
    while (duration-- > 0 && processRunning)
        asm volatile ("nop");
}
References DO_WORK_TIME_1S_MS, and processRunning.
Referenced by do_work_alarm(), do_work_sleep(), main(), signalhandler(), signalhandler_work(), t2(), t3(), t4(), and timer_callback().