système temps réel - TP2: main
main()
int main (int ac, char ** av)
We need to separate our program in 3 other process (fork).
Then we can instantiate 3 timers for each process.
Parameters
ac
av
Returns
int
Definition at line 86 of file 11-programmation-preemptive.c.
{
    signal(SIGALRM, timer_callback);
    signal(SIGINT, handleExit);
    taskId = 0;
    int periode[3] = { 2, 3, 4 };
    for (int i = 0; i < 3; i++)
    {
        taskId = i + 1;
        int pid = fork();
        if (pid == 0)
        {
            start_timer(1, periode[i]);
            while (processRunning);
            stop_timer();
        }
    }
    wait(NULL);
    wait(NULL);
    wait(NULL);
    return 0;
}
References handleExit(), processRunning, start_timer(), stop_timer(), taskId, and timer_callback().