système temps réel - TP2: main
main()
int main (int argc, char ** argv)
Main entry point of the program.
Register a signal handler and wait for 10 seconds
observation: During the 5 seconds the signalHandler function is called we can send several signals (SIGUSR1) but only 2 will be taken in consideration because the process has only a memory of 2 signals and will forget any other received signals during this time.
Exemple of output: $ process pid 8488 $ Handling signal : 10 $ Handling signal : 10
Parameters
argc
argv
Returns
int
Definition at line 50 of file 3-taches-sporadiques.c.
{
    // Register SIGUSR1 to be handled by signalHandler
    signal(SIGUSR1, signalhandler);
    // Display the PID of the process
    // to make easier the use of kill command
    displayProcessPID();
    // Simulate a work of 10 seconds
    // to let the time for user to send signal
    // from terminal
    do_work(10000);
    return 0;
}
References displayProcessPID(), do_work(), and signalhandler().