système temps réel - TP2: main
main()
int main (int ac, char ** av)
Setting up a timer of 1 second then call an infinite loop to let the timer's callback work.
observation: If the process (timer_callback) last for more than the period the timer still work but will wait the end of the process to begin another one.
Parameters
ac
av
Returns
int
Definition at line 85 of file 7-taches-periodiques.c.
{
    signal(SIGALRM, timer_callback);
    signal(SIGINT, handleExit);
    start_timer();
    while (processRunning);
    stop_timer();
}
References handleExit(), processRunning, start_timer(), stop_timer(), and timer_callback().