système temps réel - TP2: task
task()
void task ()
Execute all tasks.
Definition at line 59 of file 8-taches-periodiques.c.
            {
    t2(333);
    t3(1000);
    t4(2000);
    t2(333);
    t3(1000);
    t2(333);
    t4(2000);
    t2(333);
    t3(1000);
    t2(333);
    t4(2000);
    t3(1000);
    t2(333);
}
References t2(), t3(), and t4().
Referenced by main().